### ISSUE TITLE
Fan mode

### ISSUE THREAD

**Issue by Basfoppele** [aceindy/Duepi_EVO#32]
Hello,

Iam using scripts to call different fan modes in combination with Google Assistant.

This works great! I can tell google this way to set fan speed from 1 to 5

But after the change of 1 to 5 for min to max in climate.py 
I was unable to call HVAC fan mode medium.
Somehow this is to long and not working in a script.

I have changed medium to med in climate.py and now it's working perfect.

Best regards

Bas

**Comment by aceindy** [comment]
Send a pull request in github?

**Comment by Basfoppele** [comment]
> Are these scripts on HomeAssistant?
> 
> If possible, send a pull request in github?

Yes these scripts are on home assistant.
I will send a pull request later and will try to show what I mean 😉

**Comment by aceindy** [comment]
I understand what you want to change, I am just curious about the scripts though, as I fail to understand why the string "Medium"would be too long for a script in HA...or is GoogleAssistant the culprit?☹️ 

(and I am asking for a PullRequest just to do it the 'official way' 🧑‍🏭

**Comment by Basfoppele** [comment]
To be honest I don't know how the pull request works because I never used GitHub much before.

I can't give an answer to why medium not seems to work and med does.
But it is in HA,  because if I run the script manual in Ha it is also not working.



This is a copy of my script

alias: Pelletkachel op 3
sequence:
  - service: climate.set_fan_mode
    data:
      fan_mode: Med
    target:
      entity_id: climate.pelletkachel
mode: single

**Comment by aceindy** [comment]
Hmm..I geberuik het zelfde in Node-Red
![image](https://user-images.githubusercontent.com/94692/232329061-8d19636d-eb0a-4057-b551-071a94444d28.png)
En geen probleem met fan_mode medium :frowning: 
![image](https://user-images.githubusercontent.com/94692/232329150-19b47b7c-2307-4837-9bbd-04367b360169.png)

Maar ik zal het straks ook eens proberen met een script

**Comment by aceindy** [comment]
Hmm..
Ik heb er geen probleem mee...

```
alias: Pellet_medium
sequence:
  - service: climate.set_fan_mode
    data:
      fan_mode: Medium
    target:
      entity_id: climate.pellet_stove
mode: single
icon: mdi:fireplace

```

```
Executed: April 16, 2023 at 19:23:18
Result:
params:
  domain: climate
  service: set_fan_mode
  service_data:
    fan_mode: Medium
    entity_id:
      - climate.pellet_stove
  target:
    entity_id:
      - climate.pellet_stove
running_script: false
limit: 10

```

Home Assistant 2023.4.4
Supervisor 2023.04.0
Operating System 9.5
